using FluentNHibernate.Mapping;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MovieNetConsole
{
    public class StarMap:ClassMap<Star>
    {
        StarMap()
        {
            Id(x => x.Id); // property is int => generated by identity assumed
            Map(x => x.FullName).Column("name").Not.Nullable();
            Map(x => x.Birthdate).Nullable();
            Table("Stars");
        }
    }
}
